# Generated by Django 5.2 on 2025-04-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Student Enquiries'},
        ),
    ]
